name: Quark
version: '0.6'
main: me.startrix.quark.Quark
api-version: '1.20'
depend:
  - Slimefun
softdepend:
  - FluffyMachines
commands:
  itemstack:
    description: This is a dev command.
    usage: /<command>